services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infocomuni_api
    ports:
      - "8888:8888"
    volumes:
      - ../dati:/app/src/dati
      - ./src:/app/src
    depends_on:
      - redis
    networks:
      - infocomuni_network
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8888 --reload

  redis:
    image: redis:latest
    container_name: infocomuni_redis
    networks:
      - infocomuni_network

networks:
  infocomuni_network:
    driver: bridge
