services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infocomuni_api
    ports:
      - "8888:8888"
    volumes:
      - ../dati:/app/src/dati
      - ./src:/app/src
    networks:
      - ${NETWORK_NAME}
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app --bind 0.0.0.0:8888 --access-logfile - --error-logfile - --log-level info
    restart: unless-stopped

networks:
  ${NETWORK_NAME}:
    external: true
